# Generated by Django 4.2.18 on 2025-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
            ],
        ),
    ]
